// Regenerate web/includes-manifest.json from the EXACT include set this build
// ships. The pins (POV-Ray commit, Lightsys URL + sha256) are read straight from
// the Dockerfile so there is one source of truth: bump a pin there, run
// `npm run gen:manifest`, and the autocomplete data follows. The committed JSON
// means the static site and the browser tests never need the network or a Docker
// build to have real symbols.
//
// Two source paths, same parser (tools/includes-manifest/parse.mjs):
//   default            fetch + verify the pinned tarball + zip (the honest path)
//   POVINC_DIR=<dir>   read top-level *.inc from a local tree (offline / CI)
//
// This is build tooling: it shells out to curl/tar/unzip (same tools the
// Dockerfile uses) and is intentionally outside the coverage gate. The PARSER it
// calls is pure and unit-tested to 100%.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseManifest } from './parse.mjs';

const repoRoot = resolve(fileURLToPath(import.meta.url), '../../..');
const dockerfile = readFileSync(join(repoRoot, 'Dockerfile'), 'utf8');
const outPath = join(repoRoot, 'web/includes-manifest.json');

/** Pull a single pinned value out of the Dockerfile, or die loudly. */
function pin(re, label) {
  const m = re.exec(dockerfile);
  if (!m) throw new Error(`could not find ${label} in Dockerfile`);
  return m[1];
}

const POVRAY_COMMIT = pin(/^ARG POVRAY_COMMIT=(\S+)/m, 'POVRAY_COMMIT');
const LIGHTSYS_URL = pin(/^ARG LIGHTSYS_URL="([^"]+)"/m, 'LIGHTSYS_URL');
const LIGHTSYS_SHA256 = pin(/^ARG LIGHTSYS_SHA256="([^"]+)"/m, 'LIGHTSYS_SHA256');

/** Read every top-level .inc file in a directory into {name, text} records. */
function readIncDir(dir) {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.inc'))
    .map((name) => ({ name, text: readFileSync(join(dir, name), 'utf8') }));
}

/**
 * Fetch the pinned stdlib + Lightsys includes into a temp dir. The Dockerfile
 * embeds the WHOLE distribution/include tree, but we deliberately take only the
 * top-level *.inc files: those are the ones a scene can `#include` by bare name
 * (the dispatcher headers like stones.inc pull in the rest), so the manifest is
 * a faithful subset of the embed for completion purposes. stdlib comes from the
 * commit tarball, Lightsys from its sha256-verified zip (top-level .inc, same as
 * the Dockerfile drops in). Returns the dir.
 *
 * The pins are passed to bash as positional args ($1..$5), never interpolated
 * into the script body, so a value can't break out of the shell quoting.
 */
function fetchPinned() {
  const dir = mkdtempSync(join(tmpdir(), 'povinc-'));
  const tarball = `https://github.com/POV-Ray/povray/archive/${POVRAY_COMMIT}.tar.gz`;
  const script = `
    set -e
    cd "$1"
    curl -fsSL "$3" | tar xz "povray-$2/distribution/include"
    mv "povray-$2/distribution/include/"*.inc ./
    curl -fsSL --retry 3 -o lightsys.zip "$4"
    printf '%s  lightsys.zip\\n' "$5" | sha256sum -c -
    unzip -j -o -q lightsys.zip 'LightsysIV/*.inc' -x 'LightsysIV/*/*.inc' -d ./
  `;
  execFileSync(
    'bash',
    ['-c', script, 'bash', dir, POVRAY_COMMIT, tarball, LIGHTSYS_URL, LIGHTSYS_SHA256],
    { stdio: ['ignore', 'inherit', 'inherit'] }
  );
  return dir;
}

/**
 * Serialize one symbol object per line so a regenerated manifest produces a
 * readable, line-granular diff (prettier would explode each object across five
 * lines; the file is in .prettierignore). The metadata header records exactly
 * which sources produced it.
 */
function serialize(symbols) {
  const header =
    '{\n' +
    '  "//": "GENERATED by tools/includes-manifest/generate.mjs from the pinned POV-Ray + Lightsys sources. Do not edit by hand; run `npm run gen:manifest`.",\n' +
    `  "povrayCommit": ${JSON.stringify(POVRAY_COMMIT)},\n` +
    `  "lightsysSha256": ${JSON.stringify(LIGHTSYS_SHA256)},\n` +
    `  "count": ${symbols.length},\n` +
    '  "symbols": [\n';
  const rows = symbols.map((s) => '    ' + JSON.stringify(s)).join(',\n');
  return header + rows + '\n  ]\n}\n';
}

const local = process.env.POVINC_DIR;
const dir = local ? resolve(local) : fetchPinned();
try {
  const files = readIncDir(dir);
  if (files.length === 0) throw new Error(`no .inc files found in ${dir}`);
  const symbols = parseManifest(files);
  writeFileSync(outPath, serialize(symbols));
  process.stdout.write(
    `wrote ${symbols.length} symbols from ${files.length} files -> web/includes-manifest.json\n`
  );
} finally {
  if (!local) rmSync(dir, { recursive: true, force: true });
}
