// Inline the shared editor language modules into povrayer turbo.
//
// turbo is a single self-contained HTML file (no build, no deps, must run when
// opened as a file://), but the SDL/GLSL highlighting + autocomplete logic is
// the SAME code the web app uses. Rather than fork it, this regenerates an
// inline <script> in turbo.html from web/{highlight,context,complete,
// glsl-highlight}.js, exposing them as the globals `POVLang` and `GLSLLang`.
//
// It's a tiny purpose-built bundler: each module becomes its own IIFE keyed by
// basename (so internals like `esc`/`span` stay private and can't collide),
// `import { ... } from './x.js'` is rewritten to pull from the prior module's
// exports, and `export` is stripped while the exported names are collected into
// the IIFE's return value. Modules are listed in dependency order.
//
// Same convention as the other gen:* scripts: run `npm run gen:turbo` after
// editing those modules and commit the result. The output is prettier-formatted
// here so the committed file always passes format:check.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';
import prettier from 'prettier';

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, '..', 'web');
const TURBO = join(web, 'turbo.html');

// Dependency order: a module's imports must be bundled before it.
const MODULES = ['highlight', 'context', 'complete', 'glsl-highlight'];

const IMPORT_RE = /^import\s*\{([^}]+)\}\s*from\s*['"]\.\/([\w-]+)\.js['"];?[ \t]*$/gm;
const EXPORT_DECL_RE =
  /^export\s+((?:async\s+)?(?:function|const|let|var|class)\s+)([A-Za-z_$][\w$]*)/gm;
const EXPORT_LIST_RE = /^export\s*\{([^}]*)\}\s*;?[ \t]*$/gm;

const START = '<!-- gen:lang:start -->';
const END = '<!-- gen:lang:end -->';

/** Wrap one module as `__M['name'] = (function(){ ... return {exports}; })()`. */
function wrapModule(name) {
  let src = readFileSync(join(web, name + '.js'), 'utf8');
  const exported = new Set();
  src = src.replace(
    IMPORT_RE,
    (_m, names, mod) => `const { ${names.trim()} } = __M[${JSON.stringify(mod)}];`
  );
  src = src.replace(EXPORT_DECL_RE, (_m, decl, id) => {
    exported.add(id);
    return decl + id;
  });
  src = src.replace(EXPORT_LIST_RE, (_m, names) => {
    for (const part of names.split(',')) {
      const id = part
        .trim()
        .split(/\s+as\s+/)[0]
        .trim();
      if (id) exported.add(id);
    }
    return '';
  });
  return `__M[${JSON.stringify(name)}] = (function () {\n${src.trim()}\nreturn { ${[...exported].join(', ')} };\n})();`;
}

/** The full inline <script> block (unformatted; render() prettifies it). */
export function generate() {
  const body = MODULES.map(wrapModule).join('\n\n');
  return `<script>
// GENERATED by tools/gen-turbo.mjs from web/{${MODULES.join(', ')}}.js.
// Shared source of truth for the editor's language tooling. Do NOT edit by hand;
// run \`npm run gen:turbo\` after changing those modules.
(function () {
const __M = {};
${body}
window.POVLang = Object.assign({}, __M['highlight'], __M['context'], __M['complete']);
window.GLSLLang = __M['glsl-highlight'];
})();
</script>`;
}

/** Replace the marked region of `html` with a freshly generated block. */
export function injectInto(html) {
  const re = new RegExp(escapeRe(START) + '[\\s\\S]*?' + escapeRe(END));
  if (!re.test(html)) throw new Error('gen-turbo: gen:lang markers not found in turbo.html');
  return html.replace(re, `${START}\n${generate()}\n${END}`);
}

/** Inject, then prettier-format the whole file so the result is lint-clean. */
export async function render(html) {
  const injected = injectInto(html);
  const cfg = await prettier.resolveConfig(TURBO);
  return prettier.format(injected, { ...cfg, filepath: TURBO });
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// CLI: rewrite turbo.html in place.
if (import.meta.url === `file://${process.argv[1]}`) {
  const out = await render(readFileSync(TURBO, 'utf8'));
  writeFileSync(TURBO, out);
  console.log('gen-turbo: refreshed the inlined POVLang/GLSLLang block in turbo.html');
}
