// Inline povrayer turbo's JavaScript into its single self-contained HTML file.
//
// turbo is one HTML file (no build, no deps, must run when opened as a file://),
// but none of its JS is written there. Two generated regions:
//
//   gen:lang  the shared editor language tooling. The SDL/GLSL highlighting and
//             autocomplete are the SAME code the web app imports as modules, so
//             rather than fork it we bundle web/{highlight,context,complete,
//             glsl-highlight}.js into an inline <script> exposing the globals
//             `POVLang` and `GLSLLang`. A tiny purpose-built bundler: each module
//             becomes its own IIFE keyed by basename (so internals like
//             `esc`/`span` stay private and can't collide), `import { ... } from
//             './x.js'` is rewritten to pull from the prior module's exports, and
//             `export` is stripped while the exported names are collected into the
//             IIFE's return value. Modules are listed in dependency order.
//
//   gen:app   web/turbo-app.js, turbo's own application code, inlined VERBATIM
//             (it is already a classic script wrapped in one IIFE, so there is
//             nothing to rewrite). It lives in a real .js file purely so eslint,
//             prettier, and tsc --checkJs can see it; the shipped page is still a
//             single file with no runtime `import`.
//
// Same convention as the other gen:* scripts: run `npm run gen:turbo` after
// editing any of those files and commit the result. The output is prettier-
// formatted here so the committed file always passes format:check, and
// test/node/turbo-lang.test.mjs asserts render(committed) === committed, which
// makes a stale turbo.html uncommittable.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';
import prettier from 'prettier';

const here = dirname(fileURLToPath(import.meta.url));
const web = join(here, '..', 'web');
const TURBO = join(web, 'turbo.html');

// Dependency order: a module's imports must be bundled before it.
const MODULES = ['highlight', 'context', 'complete', 'glsl-highlight'];

const IMPORT_RE = /^import\s*\{([^}]+)\}\s*from\s*['"]\.\/([\w-]+)\.js['"];?[ \t]*$/gm;
const EXPORT_DECL_RE =
  /^export\s+((?:async\s+)?(?:function|const|let|var|class)\s+)([A-Za-z_$][\w$]*)/gm;
const EXPORT_LIST_RE = /^export\s*\{([^}]*)\}\s*;?[ \t]*$/gm;

const LANG_START = '<!-- gen:lang:start -->';
const LANG_END = '<!-- gen:lang:end -->';
const APP_START = '<!-- gen:app:start -->';
const APP_END = '<!-- gen:app:end -->';

// The application source, inlined as-is. Kept out of MODULES on purpose: it is
// not a module and needs none of the import/export rewriting.
const APP = 'turbo-app.js';

/** Wrap one module as `__M['name'] = (function(){ ... return {exports}; })()`. */
function wrapModule(name) {
  let src = readFileSync(join(web, name + '.js'), 'utf8');
  const exported = new Set();
  src = src.replace(
    IMPORT_RE,
    (_m, names, mod) => `const { ${names.trim()} } = __M[${JSON.stringify(mod)}];`
  );
  src = src.replace(EXPORT_DECL_RE, (_m, decl, id) => {
    exported.add(id);
    return decl + id;
  });
  src = src.replace(EXPORT_LIST_RE, (_m, names) => {
    for (const part of names.split(',')) {
      const id = part
        .trim()
        .split(/\s+as\s+/)[0]
        .trim();
      if (id) exported.add(id);
    }
    return '';
  });
  return `__M[${JSON.stringify(name)}] = (function () {\n${src.trim()}\nreturn { ${[...exported].join(', ')} };\n})();`;
}

/** The full inline <script> block (unformatted; render() prettifies it). */
export function generate() {
  const body = MODULES.map(wrapModule).join('\n\n');
  return `<script>
// GENERATED by tools/gen-turbo.mjs from web/{${MODULES.join(', ')}}.js.
// Shared source of truth for the editor's language tooling. Do NOT edit by hand;
// run \`npm run gen:turbo\` after changing those modules.
(function () {
const __M = {};
${body}
window.POVLang = Object.assign({}, __M['highlight'], __M['context'], __M['complete']);
window.GLSLLang = __M['glsl-highlight'];
})();
</script>`;
}

/**
 * The inline <script> holding turbo's own application code, verbatim.
 *
 * @returns {string}
 */
export function generateApp() {
  const src = readFileSync(join(web, APP), 'utf8').trim();
  return `<script>
// GENERATED by tools/gen-turbo.mjs from web/${APP} (inlined verbatim). Do NOT edit
// by hand; edit that file and run \`npm run gen:turbo\`.
${src}
</script>`;
}

/**
 * Replace one marked region of `html` with freshly generated content.
 *
 * @param {string} html
 * @param {string} start  the opening marker comment
 * @param {string} end    the closing marker comment
 * @param {string} block  the replacement body to sit between them
 * @returns {string}
 */
function replaceRegion(html, start, end, block) {
  const re = new RegExp(escapeRe(start) + '[\\s\\S]*?' + escapeRe(end));
  if (!re.test(html)) throw new Error(`gen-turbo: ${start} markers not found in turbo.html`);
  // A replacer FUNCTION, not a replacement string: `$$`, `` $` ``, `$'` and `$&`
  // are substitution patterns in a string replacement, and the inlined block is
  // thousands of lines of JS full of `$` and backticks. A future shader snippet
  // could otherwise corrupt the generated file in a way only a careful reader
  // would spot.
  return html.replace(re, () => `${start}\n${block}\n${end}`);
}

/** Replace both marked regions of `html` with freshly generated blocks. */
export function injectInto(html) {
  let out = replaceRegion(html, LANG_START, LANG_END, generate());
  out = replaceRegion(out, APP_START, APP_END, generateApp());
  return out;
}

/** Inject, then prettier-format the whole file so the result is lint-clean. */
export async function render(html) {
  const injected = injectInto(html);
  const cfg = await prettier.resolveConfig(TURBO);
  return prettier.format(injected, { ...cfg, filepath: TURBO });
}

function escapeRe(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// CLI: rewrite turbo.html in place.
if (import.meta.url === `file://${process.argv[1]}`) {
  const out = await render(readFileSync(TURBO, 'utf8'));
  writeFileSync(TURBO, out);
  console.log(`gen-turbo: refreshed the inlined lang bundle + web/${APP} in turbo.html`);
}
